Adding some structure and makefile info the getting started README
open-horizon-services/Getting-Started pull request #1
Opened 2021-06-08 01:32 UTC by t-fine

Signed-off-by: Troy Fine <Troy.Fine@ibm.com>

2021-06-22 15:14 UTC, TheMosquito commented
This looks great but could you add the other required Makefile targets (at least `agent-run` and `agent-stop`... are there others?)

2021-07-01 06:21 UTC, clementkng requested changes
Looks mostly good to me, just a couple suggestions!

2021-07-01 06:21 UTC, clementkng commented on README.md
> +## Register an Edge Node with your Mangement Hub
Typo: Management Hub

2021-07-01 06:21 UTC, clementkng commented on README.md
> +* ppc64le (support starting Horizon version 2.28)
What Horizon component does "Horizon version 2.28" this refer to?

2021-07-01 06:21 UTC, clementkng commented on README.md
> +In order to deploy a service to an edge node it must first be registered with a management hub. The `agent-install.sh` script is a fast and easy way to register an edge node with a management hub, mo
In the first sentence, it's unclear what needs to be registered with the management hub. While the second sentence makes it clear, I think the first sentence should still be something like: "The edge node must first be registered with a management hub before you can deploy a service to that node."

2021-07-01 06:21 UTC, clementkng commented on README.md
> +## Contributing
Maybe "Contributing a New Service" is a better heading, because this specifically has to do with adding a new service.

2021-07-01 06:21 UTC, clementkng commented on README.md
> +Each service in the `open-horizon-services` project has a similar structure, and set of files in an attempt to make each service as easy as possble to use.
Typo: possible

2021-07-20 16:43 UTC, t-fine commented
@clementkng Alright! I believe I finally got that dang "management" hub typo and clarified the agent in that `2.28` mention

2021-07-20 18:06 UTC, clementkng approved these changes

2021-07-20 18:07 UTC, clementkng commented
@t-fine looks great, thanks for making the changes!

2021-08-02 18:45 UTC, merged