feat : fix readme and pr templates
open-horizon-services/Getting-Started pull request #5
Opened 2022-03-03 14:42 UTC by Ayush7614

This PR contains

* Added Standard PR Template that is specially for docs and all 
* Added Issue templates

This PR template contains
## Checklist 

- [ ] The Guide has been linted against a language and grammar tool.
- [ ] The Guide is easy to follow up with and understand for new users.
- [ ] The Docsify build works locally without inducing any unwarranted changes.
It is specially use for docs and started projects

2022-03-03 14:44 UTC, Ayush7614 commented
cc @t-fine

2022-03-04 16:16 UTC, joewxboy reviewed
There is another PR with more detailed issue templates.  Can we keep the PR template in this PR but remove the issue template?

2022-03-04 19:10 UTC, Ayush7614 commented
> There is another PR with more detailed issue templates. Can we keep the PR template in this PR but remove the issue template?

Sure @joewxboy

2022-03-04 19:14 UTC, Ayush7614 commented
cc @joewxboy

2022-03-04 19:48 UTC, joewxboy commented
@Ayush7614 Don't forget to link the PR to the issue that it's based on, and add `Issue: ### - ` to the beginning of the PR title.

2022-03-04 19:55 UTC, Ayush7614 commented
> @Ayush7614 Don't forget to link the PR to the issue that it's based on, and add `Issue: ### - ` to the beginning of the PR title.

cc @joewxboy

2022-03-05 20:29 UTC, Ayush7614 commented
Cc @joewxboy

2022-03-07 19:43 UTC, Ayush7614 commented
cc @joewxboy @t-fine

2022-03-08 01:26 UTC, t-fine commented
@Ayush7614 just FYI for future PRs, I believe what @joewxboy is asking for is to select Issue #6 in the `Development` section on the right, near the top, and for the title of this PR to be in the format of how I just edited it
![Screen Shot 2022-03-07 at 5 23 29 PM](https://user-images.githubusercontent.com/25443552/157147157-e140b56b-ab50-4075-9d09-8610aeb10f75.png)

2022-03-08 03:26 UTC, t-fine requested changes

2022-03-08 03:26 UTC, t-fine commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] The Guide is easy to follow up with and understand for new users.
Do you mean this "Guide" is easy to follow and understand for new users? Or that new users are following up with this guide afterwards? If it's the former, I suggest something like "The Guide is easy to follow and understand for new users."

2022-03-08 14:48 UTC, Ayush7614 commented
cc @t-fine @joewxboy

2022-03-08 18:43 UTC, t-fine approved these changes

2022-03-08 18:47 UTC, joewxboy reviewed
What is a `Docsify` build?

2022-03-08 18:56 UTC, Ayush7614 commented
> What is a `Docsify` build?

I removed that line we can use this line later when we write proper docs it is use for docs but currently the docs and all things are not prepared

2022-03-11 15:57 UTC, Ayush7614 commented
Cc @joewxboy

2022-03-11 16:14 UTC, joewxboy approved these changes

2022-03-11 16:14 UTC, merged